Curl yq binary in dockerfile for easier updating

diff --git a/promtail/Dockerfile b/promtail/Dockerfile
--- a/promtail/Dockerfile
+++ b/promtail/Dockerfile
@@ -3,13 +3,34 @@ ARG BUILD_FROM=ghcr.io/hassio-addons/debian-base/amd64:4.1.3
 ARG BUILD_ARCH=amd64
 
 # https://github.com/mdegat01/promtail-journal/releases
-ARG PROMTAIL_BASE_VERSION=1.0.0
+FROM ghcr.io/mdegat01/promtail-journal/${BUILD_ARCH}:1.0.0 as build_promtail
 
-# https://github.com/grafana/loki/releases
-FROM ghcr.io/mdegat01/promtail-journal/${BUILD_ARCH}:${PROMTAIL_BASE_VERSION} as build
+# https://hub.docker.com/_/alpine
+FROM alpine:3.13.4 as build_yq
+# https://github.com/mikefarah/yq/releases
+ENV YQ_VERSION 4.6.3
+
+RUN set -eux; \
+    apk update; \
+    apk add --no-cache --virtual .build-deps \
+        tar=1.33-r1 \
+        curl=7.74.0-r1 \
+    ; \
+    APKARCH="$(apk --print-arch)"; \
+    case "${APKARCH}" in \
+        x86_64)  BINARCH='amd64' ;; \
+        armhf)   BINARCH='arm' ;; \
+        armv7)   BINARCH='arm' ;; \
+        aarch64) BINARCH='arm64' ;; \
+        *) echo >&2 "error: unsupported architecture (${APKARCH})"; exit 1 ;; \
+    esac; \
+    curl -J -L -o /tmp/yq.tar.gz "https://github.com/mikefarah/yq/releases/download/v${YQ_VERSION}/yq_linux_${BINARCH}.tar.gz"; \
+    tar -xf /tmp/yq.tar.gz -C /usr/bin; \
+    mv /usr/bin/yq_linux_${BINARCH} /usr/bin/yq; \
+    chmod a+x /usr/bin/yq;
 
 # hadolint ignore=DL3006
-FROM $BUILD_FROM
+FROM ${BUILD_FROM}
 
 # tzdata required for the timestamp stage to work
 # Backports repo required to get a libsystemd version 246 or newer which is required to handle journal +ZSTD compression
@@ -27,14 +48,13 @@ RUN set -eux; \
     update-ca-certificates; \
     rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*;
 
-# Add yq
-ARG BUILD_ARCH=amd64
-COPY bin/yq_linux_${BUILD_ARCH} /usr/bin/yq
-RUN yq --version
-
 # Add promtail
-COPY --from=build /usr/bin/promtail /usr/bin/promtail
+COPY --from=build_promtail /usr/bin/promtail /usr/bin/promtail
 RUN promtail --version
+
+# Add yq
+COPY --from=build_yq /usr/bin/yq /usr/bin/yq
+RUN yq --version
 
 COPY rootfs /
 WORKDIR /data/promtail
