Remove extra build layer from dockerfile

diff --git a/promtail/Dockerfile b/promtail/Dockerfile
--- a/promtail/Dockerfile
+++ b/promtail/Dockerfile
@@ -1,57 +1,52 @@
 ARG BUILD_FROM=ghcr.io/hassio-addons/debian-base/amd64
 ARG BUILD_ARCH=amd64
+ARG PROMTAIL_JOURNAL_VERSION=1.5.0
 
 # https://github.com/mdegat01/promtail-journal/releases
-FROM ghcr.io/mdegat01/promtail-journal/${BUILD_ARCH}:1.5.0 as build_promtail
-
-# https://hub.docker.com/_/alpine
-FROM alpine:3.15.4 as build_yq
-# https://github.com/mikefarah/yq/releases
-ENV YQ_VERSION 4.24.5
-
-RUN set -eux; \
-    apk update; \
-    apk add --no-cache --virtual .build-deps \
-        tar=1.34-r0 \
-        curl=7.80.0-r1 \
-    ; \
-    APKARCH="$(apk --print-arch)"; \
-    case "${APKARCH}" in \
-        x86_64)  BINARCH='amd64' ;; \
-        armhf)   BINARCH='arm' ;; \
-        armv7)   BINARCH='arm' ;; \
-        aarch64) BINARCH='arm64' ;; \
-        *) echo >&2 "error: unsupported architecture (${APKARCH})"; exit 1 ;; \
-    esac; \
-    curl -J -L -o /tmp/yq.tar.gz \
-        "https://github.com/mikefarah/yq/releases/download/v${YQ_VERSION}/yq_linux_${BINARCH}.tar.gz"; \
-    tar -xf /tmp/yq.tar.gz -C /usr/bin; \
-    mv /usr/bin/yq_linux_${BINARCH} /usr/bin/yq; \
-    chmod a+x /usr/bin/yq; \
-    rm /tmp/yq.tar.gz;
+FROM ghcr.io/mdegat01/promtail-journal/${BUILD_ARCH}:${PROMTAIL_JOURNAL_VERSION} as build_promtail
 
 # https://github.com/hassio-addons/addon-debian-base/releases
 # hadolint ignore=DL3006
 FROM ${BUILD_FROM}
 
-# tzdata required for the timestamp stage to work
+ARG BUILD_ARCH=amd64
+# https://github.com/mikefarah/yq/releases
+ARG YQ_VERSION=4.24.5
+
+# Add yq and tzdata (required for the timestamp stage)
 RUN set -eux; \
     apt-get update; \
     apt-get install -qy --no-install-recommends \ 
+        tar=1.34-r0 \
+        curl=7.74.0-1.3+deb11u1 \
         tzdata=2021a-1+deb11u3 \
         ca-certificates=20210119 \
         libsystemd-dev=247.3-7 \
         ; \
     update-ca-certificates; \
+    \
+    case "${BUILD_ARCH}" in \
+        amd64)  BINARCH='amd64' ;; \
+        armhf)   BINARCH='arm' ;; \
+        armv7)   BINARCH='arm' ;; \
+        aarch64) BINARCH='arm64' ;; \
+        *) echo >&2 "error: unsupported architecture (${APKARCH})"; exit 1 ;; \
+    esac; \
+    curl -s -J -L -o /tmp/yq.tar.gz \
+        "https://github.com/mikefarah/yq/releases/download/v${YQ_VERSION}/yq_linux_${BINARCH}.tar.gz"; \
+    tar -xf /tmp/yq.tar.gz -C /usr/bin; \
+    mv /usr/bin/yq_linux_${BINARCH} /usr/bin/yq; \
+    chmod a+x /usr/bin/yq; \
+    rm /tmp/yq.tar.gz; \
+    yq --version; \
+    \
+    apt-get purge -y --auto-remove tar; \
+    apt-get clean; \
     rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*;
 
 # Add promtail
 COPY --from=build_promtail /usr/bin/promtail /usr/bin/promtail
 RUN promtail --version
-
-# Add yq
-COPY --from=build_yq /usr/bin/yq /usr/bin/yq
-RUN yq --version
 
 COPY rootfs /
 WORKDIR /data/promtail
